-- MySQL Script generated by MySQL Workbench
-- Sun Nov 25 02:30:58 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema QuanLySach
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema QuanLySach
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `QuanLySach` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `QuanLySach` ;

-- -----------------------------------------------------
-- Table `QuanLySach`.`LoaiTaiKhoan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `QuanLySach`.`LoaiTaiKhoan` (
  `MaLoaiTaiKhoan` INT NOT NULL AUTO_INCREMENT,
  `TenLoaiTaiKhoan` VARCHAR(45) NULL,
  PRIMARY KEY (`MaLoaiTaiKhoan`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `QuanLySach`.`LoaiSach`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `QuanLySach`.`LoaiSach` (
  `MaLoaiSach` INT NOT NULL AUTO_INCREMENT,
  `TenLoaiSach` VARCHAR(64) NULL,
  `BiXoa` TINYINT(0) NULL,
  PRIMARY KEY (`MaLoaiSach`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `QuanLySach`.`NhaXuatBan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `QuanLySach`.`NhaXuatBan` (
  `MaNhaXuatBan` INT NOT NULL AUTO_INCREMENT,
  `TenNhaXuatBan` VARCHAR(64) NULL,
  `LogoURL` VARCHAR(45) NULL,
  `BiXoa` TINYINT(0) NULL,
  PRIMARY KEY (`MaNhaXuatBan`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `QuanLySach`.`TaiKhoan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `QuanLySach`.`TaiKhoan` (
  `MaTaiKhoan` INT NOT NULL AUTO_INCREMENT,
  `TenDangNhap` VARCHAR(20) NULL,
  `MatKhau` VARCHAR(20) NULL,
  `TenHienThi` VARCHAR(64) NULL,
  `DiaChi` VARCHAR(256) NULL,
  `DienThoai` VARCHAR(11) NULL,
  `Email` VARCHAR(30) NULL,
  `BiXoa` TINYINT(0) NULL,
  `MaLoaiTaiKhoan` INT NOT NULL,
  PRIMARY KEY (`MaTaiKhoan`),
  CONSTRAINT `fk_TaiKhoan_copy1_LoaiTaiKhoan1`
    FOREIGN KEY (`MaLoaiTaiKhoan`)
    REFERENCES `QuanLySach`.`LoaiTaiKhoan` (`MaLoaiTaiKhoan`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `QuanLySach`.`TinhTrang`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `QuanLySach`.`TinhTrang` (
  `MaTinhTrang` INT NOT NULL AUTO_INCREMENT,
  `TenTinhTrang` VARCHAR(45) NULL,
  PRIMARY KEY (`MaTinhTrang`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `QuanLySach`.`DonDatHang`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `QuanLySach`.`DonDatHang` (
  `MaDonDatHang` VARCHAR(9) NOT NULL,
  `NgayLap` DATETIME NULL,
  `TongThanhTien` INT NULL,
  `MaTaiKhoan` INT NOT NULL,
  `MaTinhTrang` INT NOT NULL,
  PRIMARY KEY (`MaDonDatHang`),
  CONSTRAINT `fk_DonDatHang_TaiKhoan1`
    FOREIGN KEY (`MaTaiKhoan`)
    REFERENCES `QuanLySach`.`TaiKhoan` (`MaTaiKhoan`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DonDatHang_TinhTrang1`
    FOREIGN KEY (`MaTinhTrang`)
    REFERENCES `QuanLySach`.`TinhTrang` (`MaTinhTrang`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `QuanLySach`.`Sach`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `QuanLySach`.`Sach` (
  `MaSach` INT NOT NULL AUTO_INCREMENT,
  `TenSach` VARCHAR(45) NULL,
  `HinhURL` VARCHAR(45) NULL,
  `GiaSach` INT NULL,
  `NgayNhap` DATETIME NULL,
  `SoLuongTon` INT NULL,
  `SoLuongBan` INT NULL,
  `SoLuocXem` INT NULL,
  `MoTa` TEXT NULL,
  `BiXoa` TINYINT(0) NULL,
  `MaLoaiSach` INT NOT NULL,
  `MaNhaXuatBan` INT NOT NULL,
  PRIMARY KEY (`MaSach`),
  CONSTRAINT `fk_SanPham_LoaiSanPham1`
    FOREIGN KEY (`MaLoaiSach`)
    REFERENCES `QuanLySach`.`LoaiSach` (`MaLoaiSach`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SanPham_HangSanXuat1`
    FOREIGN KEY (`MaNhaXuatBan`)
    REFERENCES `QuanLySach`.`NhaXuatBan` (`MaNhaXuatBan`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `QuanLySach`.`ChiTietDonDatHang`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `QuanLySach`.`ChiTietDonDatHang` (
  `MaChiTietDonDatHang` VARCHAR(11) NOT NULL,
  `SoLuong` INT NULL,
  `GiaBan` INT NULL,
  `MaDonDatHang` VARCHAR(9) NOT NULL,
  `MaSach` INT NOT NULL,
  PRIMARY KEY (`MaChiTietDonDatHang`),
  CONSTRAINT `fk_ChiTietDonDatHang_DonDatHang1`
    FOREIGN KEY (`MaDonDatHang`)
    REFERENCES `QuanLySach`.`DonDatHang` (`MaDonDatHang`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ChiTietDonDatHang_SanPham1`
    FOREIGN KEY (`MaSach`)
    REFERENCES `QuanLySach`.`Sach` (`MaSach`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `QuanLySach`.`TacGia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `QuanLySach`.`TacGia` (
  `MaTacGia` VARCHAR(20) NOT NULL,
  `TenTacGia` VARCHAR(50) NULL,
  `NgaySinh` DATETIME NULL,
  `TieuSu` TEXT NULL,
  PRIMARY KEY (`MaTacGia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `QuanLySach`.`TacGia_has_Sach`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `QuanLySach`.`TacGia_has_Sach` (
  `TacGia_MaTacGia` VARCHAR(20) NOT NULL,
  `Sach_MaSach` INT NOT NULL,
  PRIMARY KEY (`TacGia_MaTacGia`, `Sach_MaSach`),
  CONSTRAINT `fk_TacGia_has_Sach_TacGia1`
    FOREIGN KEY (`TacGia_MaTacGia`)
    REFERENCES `QuanLySach`.`TacGia` (`MaTacGia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TacGia_has_Sach_Sach1`
    FOREIGN KEY (`Sach_MaSach`)
    REFERENCES `QuanLySach`.`Sach` (`MaSach`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
